global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 3s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  enable_http2: false
  static_configs:
  - targets:
    - host.docker.internal:5255